
#[general] # uncomment this line of code after alacritty update to 0.14 
import = ["/home/pc/repos/Debtorchy/ubuntu-utility/dotfiles/alacritty/themes/gruvbox-material-medium-dark.toml"]


[window]
opacity = 0.95

[font]
normal.family = "Code New Roman Nerd Font"
normal.style = "Regular"
size = 12.0

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Underline", blinking = "Never" }
unfocused_hollow = false
blink_interval = 700
blink_timeout = 0
thickness = 0.2

[keyboard]
bindings = [

    { key = "N", mods = "Control | Shift", command = "alacritty" }

]

